# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2016


# 地形を破壊するかどうか
destructTerrain: true

# 爆発の大きさ（爆発力の目安：1.0=ガストの火球、3.0=クリーパーの爆発、4.0=TNTの爆発）
explosionPower: 15.0

# 魔法の弾速。あまり速くし過ぎると弾道が荒ぶるので、ほどほどにしておくこと。
magicSpeed: 3.0

# スペル
# 爆裂魔法を発動するために、チャットで詠唱しなければならない内容
# (A|B) のように記載されている内容は、AでもBでも、どちらでも構いません。
# 句読点やビックリマーク、半角空白、全角空白は、すべて無視されます。
spells:

  # 第2話
  spell1:
  - '黒より黒く闇より暗き漆黒に'
  - '我が真紅の(混淆|混交|こんこう)を望みたもう'
  - '覚醒の時来たれり(無謬|むびゅう)の境界に落ちし理'
  - '無行の歪みとなれて現出せよ'
  - '踊れ踊れ踊れ'
  - '我が力の本流に望むは崩壊なり'
  - '並ぶ者無き崩壊なり'
  - '万象等しく(灰燼|かいじん)に帰し深淵より来たれ'
  - 'これが人類最大の威力の攻撃手段'
  - 'これこそが究極の攻撃魔法'
  - 'エクスプロージョン！'

  # 第3話
  spell2:
  - '光に覆われし漆黒よ夜を纏いし爆炎よ'
  - '紅魔の名の下に原初の崩壊を(顕現|けんげん)す'
  - '終焉の王国の地に力の根源を隠匿せし者'
  - '我が前に統べよ'
  - 'エクスプロージョン！'

  # 第4話
  spell3:
  - '(赫き|赤き|あかき)黒炎'
  - '万壊の王'
  - '天地の法を(敷衍|布衍|敷延|ふえん)すれど我は万象四(耀|よう)の理'
  - '崩壊破壊の別名なり'
  - '永劫の鉄槌は我が元に下れ'
  - 'エクスプロージョン！'

  # 第10話1回目
  spell4:
  - '黒より黒く闇より暗き漆黒に'
  - '我が真紅の(混淆|混交|こんこう)を望みたもう'
  - '覚醒の時来たれり(無謬|むびゅう)の境界に落ちし理'
  - '無行の歪みとなれて現出せよ'
  - 'エクスプロージョン！'

  # 第10話2回目
  spell5:
  - '光に覆われし漆黒よ夜を纏いし爆炎よ'
  # - '他はともかく、爆裂魔法のことに関しては、私は誰にも負けたくないのです！'
  # - 'いきます！'
  - '我が究極の破壊魔法'
  - 'エクスプロージョン！'
